const asyncHandler = require('express-async-handler');
const bcrypt = require('bcryptjs');
const mongoose = require('mongoose');
const Tenant = require('../models/tenantModel');
const { PLAN_CATALOG } = require('../models/tenantModel');
const User = require('../models/userModel');
const PlatformAudit = require('../models/platformAuditModel');
const PlatformConfig = require('../models/platformConfigModel');
const { effectivePlanFeatures, invalidateFeatureCache, ALL_FEATURES } = require('../config/features');
const generateToken = require('../utils/generateToken');
const { seedTenantSettings } = require('./appSettingsController');

// Resolve a single plan's {label, price, maxUsers, maxProducts} from the
// editable DB catalog, falling back to the hardcoded defaults.
const resolvePlan = async (planKey) => {
  try {
    const cfg = await PlatformConfig.getCatalog();
    const plan = cfg.plans?.[planKey];
    if (plan) return plan.toObject ? plan.toObject() : plan;
  } catch { /* fall through */ }
  return PLAN_CATALOG[planKey] || PLAN_CATALOG.trial;
};

// Helper: compute live counts for a list of tenantIds
const getLiveStats = async (tenantIds) => {
  if (!tenantIds.length) return {};

  const [users, products, sales] = await Promise.all([
    User.aggregate([
      { $match: { tenantId: { $in: tenantIds } } },
      { $group: { _id: '$tenantId', count: { $sum: 1 } } },
    ]),
    mongoose.modelNames().includes('Product')
      ? mongoose.model('Product').aggregate([
          { $match: { tenantId: { $in: tenantIds } } },
          { $group: { _id: '$tenantId', count: { $sum: 1 } } },
        ])
      : Promise.resolve([]),
    mongoose.modelNames().includes('Sale')
      ? mongoose.model('Sale').aggregate([
          { $match: { tenantId: { $in: tenantIds } } },
          { $group: { _id: '$tenantId', count: { $sum: 1 } } },
        ])
      : Promise.resolve([]),
  ]);

  const toMap = (arr) => Object.fromEntries(arr.map((r) => [r._id.toString(), r.count]));
  const uMap = toMap(users);
  const pMap = toMap(products);
  const sMap = toMap(sales);

  const result = {};
  tenantIds.forEach((id) => {
    const k = id.toString();
    result[k] = { userCount: uMap[k] || 0, productCount: pMap[k] || 0, saleCount: sMap[k] || 0 };
  });
  return result;
};

const isExpired = (t) =>
  t.status === 'expired' ||
  (t.status === 'trial' && t.trialEndsAt && new Date() > new Date(t.trialEndsAt));

// ── Public: Register a new tenant (shop owner signup) ──
// POST /api/tenants/register
const registerTenant = asyncHandler(async (req, res) => {
  const { shopName, ownerName, ownerEmail, ownerPhone, password } = req.body;

  if (!shopName || !ownerName || !ownerEmail || !password) {
    res.status(400);
    throw new Error('Nom de la boutique, nom du propriétaire, email et mot de passe sont requis.');
  }

  if (password.length < 6) {
    res.status(400);
    throw new Error('Le mot de passe doit contenir au moins 6 caractères.');
  }

  // Check email not already used as tenant owner
  const existingTenant = await Tenant.findOne({ ownerEmail: ownerEmail.toLowerCase() });
  if (existingTenant) {
    res.status(409);
    throw new Error('Un compte existe déjà avec cet email.');
  }

  // Create tenant first (slug + code auto-generated by pre-save hook)
  const trialPlan = await resolvePlan('trial');
  const tenant = await Tenant.create({
    name: shopName.trim(),
    ownerName: ownerName.trim(),
    ownerEmail: ownerEmail.toLowerCase().trim(),
    ownerPhone: ownerPhone ? ownerPhone.trim() : '',
    monthlyPrice: trialPlan.price || 0,
    maxUsers: trialPlan.maxUsers,
    maxProducts: trialPlan.maxProducts,
    branding: { appName: shopName.trim() },
  });

  // Create the admin user for this tenant
  const adminUser = await User.create({
    tenantId: tenant._id,
    name: ownerName.trim(),
    email: ownerEmail.toLowerCase().trim(),
    phone: ownerPhone ? ownerPhone.trim() : '',
    password,
    isAdmin: true,
    isActive: true,
  });

  // Seed this shop's Settings with the info entered at creation
  await seedTenantSettings({
    tenantId: tenant._id,
    shopName: tenant.name,
    ownerEmail: tenant.ownerEmail,
    ownerPhone: tenant.ownerPhone,
    primaryColor: tenant.branding?.primaryColor,
  });

  // Update tenant stats
  await Tenant.findByIdAndUpdate(tenant._id, { 'stats.userCount': 1 });

  const token = generateToken(adminUser._id, tenant._id);

  res.status(201).json({
    token,
    tenant: {
      _id: tenant._id,
      name: tenant.name,
      slug: tenant.slug,
      code: tenant.code,
      plan: tenant.plan,
      status: tenant.status,
      trialEndsAt: tenant.trialEndsAt,
      branding: tenant.branding,
    },
    user: {
      _id: adminUser._id,
      name: adminUser.name,
      email: adminUser.email,
      isAdmin: true,
    },
  });
});

// ── Super-admin: list all tenants ──
// GET /api/tenants
const getTenants = asyncHandler(async (req, res) => {
  // Optional filters: ?status=trial&plan=basic&search=omar
  const filter = {};
  if (req.query.status) filter.status = req.query.status;
  if (req.query.plan)   filter.plan   = req.query.plan;
  if (req.query.search) {
    const re = new RegExp(req.query.search.replace(/[.*+?^${}()|[\]\\]/g, '\\$&'), 'i');
    filter.$or = [{ name: re }, { ownerEmail: re }, { ownerName: re }, { code: re }];
  }

  const tenants = await Tenant.find(filter).sort({ createdAt: -1 }).lean();

  // Live counts for all returned tenants
  const statsMap = await getLiveStats(tenants.map((t) => t._id));

  res.json(
    tenants.map((t) => {
      const live = statsMap[t._id.toString()] || {};
      return {
        ...t,
        stats: { ...t.stats, ...live },
        isActive: t.status !== 'suspended' && !isExpired(t),
      };
    })
  );
});

// ── Super-admin: get single tenant ──
// GET /api/tenants/:id
const getTenantById = asyncHandler(async (req, res) => {
  const tenant = await Tenant.findById(req.params.id).lean();
  if (!tenant) {
    res.status(404);
    throw new Error('Boutique introuvable.');
  }

  const [users, statsMap] = await Promise.all([
    User.find({ tenantId: tenant._id })
      .select('name email isAdmin isActive lastLogin lastActivity')
      .lean(),
    getLiveStats([tenant._id]),
  ]);

  const live = statsMap[tenant._id.toString()] || {};
  res.json({
    ...tenant,
    stats: { ...tenant.stats, ...live },
    isActive: tenant.status !== 'suspended' && !isExpired(tenant),
    users,
  });
});

// ── Super-admin: update tenant status / plan ──
// PUT /api/tenants/:id
const updateTenant = asyncHandler(async (req, res) => {
  const { status, plan, maxUsers, maxProducts, subscriptionEndsAt, billingNotes, branding } = req.body;

  const tenant = await Tenant.findById(req.params.id);
  if (!tenant) {
    res.status(404);
    throw new Error('Boutique introuvable.');
  }

  const before = { status: tenant.status, plan: tenant.plan };

  if (status) tenant.status = status;

  // Changing the plan cascades the catalog price + limits (still overridable below).
  if (plan && plan !== tenant.plan) {
    tenant.plan = plan;
    const cat = await resolvePlan(plan);
    if (cat) {
      tenant.monthlyPrice = cat.price;
      tenant.maxUsers = cat.maxUsers;
      tenant.maxProducts = cat.maxProducts;
    }
  }

  if (maxUsers !== undefined) tenant.maxUsers = Number(maxUsers);
  if (maxProducts !== undefined) tenant.maxProducts = Number(maxProducts);
  if (req.body.monthlyPrice !== undefined) tenant.monthlyPrice = Number(req.body.monthlyPrice) || 0;
  if (subscriptionEndsAt) tenant.subscriptionEndsAt = new Date(subscriptionEndsAt);
  if (req.body.nextPaymentDue) tenant.nextPaymentDue = new Date(req.body.nextPaymentDue);
  if (req.body.trialEndsAt) tenant.trialEndsAt = new Date(req.body.trialEndsAt);
  if (billingNotes !== undefined) tenant.billingNotes = billingNotes;
  if (req.body.dialCode !== undefined) {
    // Keep only digits and a single leading "+", normalised to "+<digits>".
    const raw = String(req.body.dialCode).replace(/[^\d+]/g, '').replace(/(?!^)\+/g, '');
    tenant.dialCode = raw ? (raw.startsWith('+') ? raw : `+${raw.replace(/^0+/, '')}`) : '';
  }
  if (branding) tenant.branding = { ...tenant.branding, ...branding };

  // Per-shop feature overrides — keep only known features with boolean values.
  if (req.body.featureOverrides && typeof req.body.featureOverrides === 'object') {
    const clean = {};
    ALL_FEATURES.forEach((key) => {
      const v = req.body.featureOverrides[key];
      if (v === true || v === false) clean[key] = v;
    });
    tenant.featureOverrides = clean;
    tenant.markModified('featureOverrides');
  }

  await tenant.save();

  // Audit the meaningful state changes
  if (status && status !== before.status) {
    const action = status === 'suspended' ? 'tenant.suspend'
      : (before.status === 'suspended' ? 'tenant.reactivate' : 'tenant.update');
    PlatformAudit.record({ req, action, tenant, meta: { from: before.status, to: status, reason: req.body.reason || '' } });
  }
  if (plan && plan !== before.plan) {
    PlatformAudit.record({ req, action: 'tenant.plan_change', tenant, meta: { from: before.plan, to: plan } });
  }

  res.json(tenant);
});

// ── Super-admin: delete a tenant and all its data ──
// DELETE /api/tenants/:id
const deleteTenant = asyncHandler(async (req, res) => {
  const tenant = await Tenant.findById(req.params.id);
  if (!tenant) {
    res.status(404);
    throw new Error('Boutique introuvable.');
  }

  const tid = tenant._id;

  // Cascade delete across all tenant-scoped collections
  const mongoose = require('mongoose');
  const modelNames = [
    'User', 'Product', 'Sale', 'Client', 'Employee',
    'Expense', 'BankTransaction', 'AdminRequest', 'Document',
    'AppSettings', 'Category', 'Container', 'Warehouse',
    'Supplier', 'ExpenseCategory', 'DeletedSale',
  ];
  await Promise.all(
    modelNames.map((name) => {
      try {
        return mongoose.model(name).deleteMany({ tenantId: tid });
      } catch {
        return Promise.resolve();
      }
    })
  );

  PlatformAudit.record({ req, action: 'tenant.delete', tenant, meta: { code: tenant.code, ownerEmail: tenant.ownerEmail } });

  await Tenant.findByIdAndDelete(tid);

  res.json({ message: 'Boutique et toutes ses données supprimées.' });
});

// ── Authenticated: get own tenant info ──
// GET /api/tenants/me
const getMyTenant = asyncHandler(async (req, res) => {
  if (!req.tenantId) {
    return res.json(null);
  }
  const tenant = await Tenant.findById(req.tenantId)
    .select('name slug code plan status trialEndsAt subscriptionEndsAt branding maxUsers maxProducts planRequest dialCode')
    .lean();
  if (!tenant) {
    res.status(404);
    throw new Error('Boutique introuvable.');
  }
  res.json(tenant);
});

// ── Super-admin: impersonate a tenant's admin user ──
// POST /api/tenants/:id/impersonate
// Returns a short-lived token scoped to that tenant so the super-admin
// can log in as the shop owner for debugging / support.
const impersonateTenant = asyncHandler(async (req, res) => {
  const tenant = await Tenant.findById(req.params.id);
  if (!tenant) {
    res.status(404);
    throw new Error('Boutique introuvable.');
  }

  // Find the primary admin of this tenant
  const adminUser = await User.findOne({ tenantId: tenant._id, isAdmin: true, isActive: true })
    .sort({ createdAt: 1 })
    .lean();

  if (!adminUser) {
    res.status(404);
    throw new Error('Aucun administrateur actif trouvé pour cette boutique.');
  }

  // Issue a token valid 2 hours — shorter than normal 30d
  const jwt = require('jsonwebtoken');
  const token = jwt.sign(
    { id: adminUser._id, tenantId: tenant._id.toString(), impersonatedBy: req.user._id.toString() },
    process.env.JWT_SECRET,
    { expiresIn: '2h' }
  );

  PlatformAudit.record({ req, action: 'tenant.impersonate', tenant, meta: { asUser: adminUser.email } });

  res.json({
    token,
    tenant: { _id: tenant._id, name: tenant.name, code: tenant.code },
    user:   { _id: adminUser._id, name: adminUser.name, email: adminUser.email, isAdmin: true },
    expiresIn: '2h',
  });
});

// ── Super-admin: create a tenant directly from the panel ──
// POST /api/tenants
const createTenant = asyncHandler(async (req, res) => {
  const { shopName, ownerName, ownerEmail, ownerPhone, password, plan, status, subscriptionEndsAt } = req.body;

  if (!shopName || !ownerName || !ownerEmail || !password) {
    res.status(400);
    throw new Error('Nom boutique, propriétaire, email et mot de passe requis.');
  }

  const existingTenant = await Tenant.findOne({ ownerEmail: ownerEmail.toLowerCase() });
  if (existingTenant) {
    res.status(409);
    throw new Error('Un compte existe déjà avec cet email.');
  }

  const chosenPlan = plan || 'trial';
  const cat = await resolvePlan(chosenPlan);
  const tenant = await Tenant.create({
    name:        shopName.trim(),
    ownerName:   ownerName.trim(),
    ownerEmail:  ownerEmail.toLowerCase().trim(),
    ownerPhone:  ownerPhone ? ownerPhone.trim() : '',
    plan:        chosenPlan,
    status:      status || 'trial',
    monthlyPrice: cat.price,
    maxUsers:    cat.maxUsers,
    maxProducts: cat.maxProducts,
    subscriptionEndsAt: subscriptionEndsAt ? new Date(subscriptionEndsAt) : null,
    branding:    { appName: shopName.trim() },
  });

  const adminUser = await User.create({
    tenantId: tenant._id,
    name:     ownerName.trim(),
    email:    ownerEmail.toLowerCase().trim(),
    phone:    ownerPhone ? ownerPhone.trim() : '',
    password,
    isAdmin:  true,
    isActive: true,
  });

  // Seed this shop's Settings with the info entered at creation
  await seedTenantSettings({
    tenantId: tenant._id,
    shopName: tenant.name,
    ownerEmail: tenant.ownerEmail,
    ownerPhone: tenant.ownerPhone,
    primaryColor: tenant.branding?.primaryColor,
  });

  await Tenant.findByIdAndUpdate(tenant._id, { 'stats.userCount': 1 });

  PlatformAudit.record({ req, action: 'tenant.create', tenant, meta: { plan: chosenPlan, byPanel: true } });

  res.status(201).json({ tenant, adminUserId: adminUser._id });
});

// ── Super-admin: export tenants to CSV ──
// GET /api/tenants/export/csv
const exportTenantsCsv = asyncHandler(async (req, res) => {
  const tenants = await Tenant.find({}).sort({ createdAt: -1 }).lean();
  const statsMap = await getLiveStats(tenants.map((t) => t._id));

  const header = ['Code', 'Boutique', 'Proprietaire', 'Email', 'Tel', 'Plan', 'Statut', 'Utilisateurs', 'Produits', 'Ventes', 'Creee le', 'Fin essai', 'Fin abonnement'];

  const rows = tenants.map((t) => {
    const s = statsMap[t._id.toString()] || {};
    return [
      t.code,
      t.name,
      t.ownerName,
      t.ownerEmail,
      t.ownerPhone || '',
      t.plan,
      t.status,
      s.userCount || 0,
      s.productCount || 0,
      s.saleCount || 0,
      t.createdAt ? new Date(t.createdAt).toLocaleDateString('fr-FR') : '',
      t.trialEndsAt ? new Date(t.trialEndsAt).toLocaleDateString('fr-FR') : '',
      t.subscriptionEndsAt ? new Date(t.subscriptionEndsAt).toLocaleDateString('fr-FR') : '',
    ].map((v) => `"${String(v).replace(/"/g, '""')}"`).join(',');
  });

  const csv = [header.join(','), ...rows].join('\n');
  res.setHeader('Content-Type', 'text/csv; charset=utf-8');
  res.setHeader('Content-Disposition', `attachment; filename="boutiques-${new Date().toISOString().slice(0,10)}.csv"`);
  res.send('﻿' + csv); // BOM for Excel UTF-8
});

// ── Super-admin: platform overview stats (revenue, funnel, attention) ──
// GET /api/tenants/stats/overview
const getOverviewStats = asyncHandler(async (req, res) => {
  const tenants = await Tenant.find({}).lean();
  const now = new Date();
  const startOfMonth = new Date(now.getFullYear(), now.getMonth(), 1);

  const paying = tenants.filter((t) => t.status === 'active');
  const trials = tenants.filter((t) => t.status === 'trial' && !isExpired(t));
  const suspended = tenants.filter((t) => t.status === 'suspended');
  const churned = tenants.filter((t) => t.status === 'expired' || (t.status === 'trial' && isExpired(t)));

  // MRR = sum of monthlyPrice for active (paying) tenants
  const mrr = paying.reduce((sum, t) => sum + (t.monthlyPrice || 0), 0);

  // Revenue collected this month (from payment records)
  let revenueThisMonth = 0;
  tenants.forEach((t) => {
    (t.payments || []).forEach((p) => {
      if (p.paidAt && new Date(p.paidAt) >= startOfMonth) revenueThisMonth += p.amount || 0;
    });
  });

  // Signups over the last 6 months
  const signups = {};
  for (let i = 5; i >= 0; i -= 1) {
    const d = new Date(now.getFullYear(), now.getMonth() - i, 1);
    signups[`${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, '0')}`] = 0;
  }
  tenants.forEach((t) => {
    const d = new Date(t.createdAt);
    const key = `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, '0')}`;
    if (key in signups) signups[key] += 1;
  });

  // Plan distribution
  const planDist = {};
  tenants.forEach((t) => { planDist[t.plan] = (planDist[t.plan] || 0) + 1; });

  // Growth & churn over the last 6 months: new shops (createdAt) vs lost shops
  // (suspend events from the audit log). Reactivations net the loss back.
  const growth = {};
  for (let i = 5; i >= 0; i -= 1) {
    const d = new Date(now.getFullYear(), now.getMonth() - i, 1);
    growth[`${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, '0')}`] = { new: 0, lost: 0 };
  }
  Object.keys(signups).forEach((key) => { if (growth[key]) growth[key].new = signups[key]; });
  const sixMonthsAgo = new Date(now.getFullYear(), now.getMonth() - 5, 1);
  const churnEvents = await PlatformAudit.find({
    action: { $in: ['tenant.suspend', 'tenant.reactivate'] },
    createdAt: { $gte: sixMonthsAgo },
  }).select('action createdAt').lean();
  churnEvents.forEach((ev) => {
    const d = new Date(ev.createdAt);
    const key = `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, '0')}`;
    if (!growth[key]) return;
    if (ev.action === 'tenant.suspend') growth[key].lost += 1;
    else if (ev.action === 'tenant.reactivate') growth[key].lost = Math.max(0, growth[key].lost - 1);
  });
  // Current-month churn rate = lost this month / shops active at month start.
  const monthKeys = Object.keys(growth);
  const lastKey = monthKeys[monthKeys.length - 1];
  const lostThisMonth = growth[lastKey]?.lost || 0;
  const activeBase = paying.length + lostThisMonth;
  const churnRate = activeBase > 0 ? Math.round((lostThisMonth / activeBase) * 1000) / 10 : 0;

  // Attention lists
  const liveStats = await getLiveStats(tenants.map((t) => t._id));
  const soon = 3 * 86400000;
  const inactiveCutoff = new Date(now - 14 * 86400000);

  const trialsExpiring = trials
    .filter((t) => t.trialEndsAt && new Date(t.trialEndsAt) - now <= soon)
    .map((t) => ({ _id: t._id, name: t.name, trialEndsAt: t.trialEndsAt }));

  const paymentsOverdue = tenants
    .filter((t) => t.status === 'active' && t.nextPaymentDue && new Date(t.nextPaymentDue) < now)
    .map((t) => ({ _id: t._id, name: t.name, nextPaymentDue: t.nextPaymentDue, amount: t.monthlyPrice }));

  const dormant = tenants
    .filter((t) => t.status !== 'suspended' && (!t.stats?.lastActiveAt || new Date(t.stats.lastActiveAt) < inactiveCutoff))
    .map((t) => ({ _id: t._id, name: t.name, lastActiveAt: t.stats?.lastActiveAt || null }));

  const nearLimit = tenants
    .map((t) => {
      const s = liveStats[t._id.toString()] || {};
      const userPct = t.maxUsers ? (s.userCount || 0) / t.maxUsers : 0;
      const prodPct = t.maxProducts ? (s.productCount || 0) / t.maxProducts : 0;
      const pct = Math.max(userPct, prodPct);
      return { _id: t._id, name: t.name, pct, userCount: s.userCount || 0, maxUsers: t.maxUsers, productCount: s.productCount || 0, maxProducts: t.maxProducts };
    })
    .filter((t) => t.pct >= 0.8);

  res.json({
    revenue: { mrr, arr: mrr * 12, revenueThisMonth },
    funnel: {
      total: tenants.length,
      paying: paying.length,
      trials: trials.length,
      suspended: suspended.length,
      churned: churned.length,
    },
    signups,
    planDist,
    growth,
    churnRate,
    attention: { trialsExpiring, paymentsOverdue, dormant, nearLimit },
  });
});

// ── Super-admin: record a payment for a tenant ──
// POST /api/tenants/:id/payment
const recordPayment = asyncHandler(async (req, res) => {
  const { amount, method, period, note, nextPaymentDue } = req.body;
  const numericAmount = Number(amount);
  if (!Number.isFinite(numericAmount) || numericAmount <= 0) {
    res.status(400);
    throw new Error('Montant invalide.');
  }

  const tenant = await Tenant.findById(req.params.id);
  if (!tenant) {
    res.status(404);
    throw new Error('Boutique introuvable.');
  }

  const paidAt = new Date();
  tenant.payments.push({
    amount: numericAmount,
    method: method || 'cash',
    period: period || `${paidAt.getFullYear()}-${String(paidAt.getMonth() + 1).padStart(2, '0')}`,
    note: note || '',
    recordedBy: req.user._id,
    paidAt,
  });
  tenant.lastPaymentAt = paidAt;
  if (nextPaymentDue) tenant.nextPaymentDue = new Date(nextPaymentDue);
  // A payment on a trial/suspended shop activates it.
  if (tenant.status !== 'active') tenant.status = 'active';

  await tenant.save();

  PlatformAudit.record({ req, action: 'tenant.payment', tenant, meta: { amount: numericAmount, method: method || 'cash', period } });

  res.status(201).json(tenant);
});

// ── Super-admin: platform audit log ──
// GET /api/tenants/audit?limit=100
const getAuditLog = asyncHandler(async (req, res) => {
  const limit = Math.min(Number(req.query.limit) || 100, 500);
  const filter = {};
  if (req.query.tenant) filter.targetTenant = req.query.tenant;
  if (req.query.action) filter.action = req.query.action;

  const logs = await PlatformAudit.find(filter)
    .sort({ createdAt: -1 })
    .limit(limit)
    .lean();

  res.json(logs);
});

// ── Super-admin: full statistics profile for ONE shop ──
// GET /api/tenants/:id/stats
const getTenantStats = asyncHandler(async (req, res) => {
  const tenant = await Tenant.findById(req.params.id).lean();
  if (!tenant) {
    res.status(404);
    throw new Error('Boutique introuvable.');
  }
  const tid = tenant._id;
  const now = new Date();
  const startOfMonth = new Date(now.getFullYear(), now.getMonth(), 1);
  const startOfLastMonth = new Date(now.getFullYear(), now.getMonth() - 1, 1);
  const sixMonthsAgo = new Date(now.getFullYear(), now.getMonth() - 5, 1);
  const sevenDaysAgo = new Date(now.getTime() - 7 * 86400000);

  const model = (name) => (mongoose.modelNames().includes(name) ? mongoose.model(name) : null);
  const Sale = model('Sale');
  const Product = model('Product');
  const Client = model('Client');
  const Employee = model('Employee');
  const Expense = model('Expense');

  const safeAgg = (m, pipeline) => (m ? m.aggregate(pipeline) : Promise.resolve([]));
  const safeCount = (m, filter) => (m ? m.countDocuments(filter) : Promise.resolve(0));

  const [
    productCount, clientCount, employeeCount, userCount, activeUsers,
    salesAgg, monthAgg, statusAgg, outstandingAgg, stockAgg, expenseAgg, trendAgg, topProductsAgg,
    lastSale,
  ] = await Promise.all([
    safeCount(Product, { tenantId: tid }),
    safeCount(Client, { tenantId: tid }),
    safeCount(Employee, { tenantId: tid }),
    User.countDocuments({ tenantId: tid }),
    User.countDocuments({ tenantId: tid, lastActivity: { $gte: sevenDaysAgo } }),

    safeAgg(Sale, [
      { $match: { tenantId: tid, status: { $ne: 'cancelled' } } },
      { $group: { _id: null, count: { $sum: 1 }, revenue: { $sum: '$totalAmount' }, profit: { $sum: '$profitData.totalProfit' } } },
    ]),
    safeAgg(Sale, [
      { $match: { tenantId: tid, status: { $ne: 'cancelled' }, saleDate: { $gte: startOfLastMonth } } },
      { $group: { _id: { $cond: [{ $gte: ['$saleDate', startOfMonth] }, 'this', 'last'] }, revenue: { $sum: '$totalAmount' }, count: { $sum: 1 } } },
    ]),
    safeAgg(Sale, [
      { $match: { tenantId: tid } },
      { $group: { _id: '$status', count: { $sum: 1 } } },
    ]),
    safeAgg(Sale, [
      { $match: { tenantId: tid, status: { $in: ['pending', 'partially_paid'] } } },
      { $project: { totalAmount: 1, paid: { $sum: '$payments.amount' } } },
      { $group: { _id: null, outstanding: { $sum: { $subtract: ['$totalAmount', '$paid'] } }, count: { $sum: 1 } } },
    ]),
    safeAgg(Product, [
      { $match: { tenantId: tid } },
      { $group: {
        _id: null,
        stockValue: { $sum: { $multiply: [{ $ifNull: ['$price', 0] }, { $ifNull: ['$stock', 0] }] } },
        stockUnits: { $sum: { $ifNull: ['$stock', 0] } },
        outOfStock: { $sum: { $cond: [{ $lte: [{ $ifNull: ['$stock', 0] }, 0] }, 1, 0] } },
        lowStock: { $sum: { $cond: [{ $and: [{ $gt: ['$stock', 0] }, { $lte: ['$stock', 5] }] }, 1, 0] } },
      } },
    ]),
    safeAgg(Expense, [
      { $match: { tenantId: tid } },
      { $group: { _id: null, total: { $sum: '$amount' }, count: { $sum: 1 } } },
    ]),
    safeAgg(Sale, [
      { $match: { tenantId: tid, status: { $ne: 'cancelled' }, saleDate: { $gte: sixMonthsAgo } } },
      { $group: { _id: { y: { $year: '$saleDate' }, m: { $month: '$saleDate' } }, revenue: { $sum: '$totalAmount' }, count: { $sum: 1 } } },
    ]),
    safeAgg(Sale, [
      { $match: { tenantId: tid, status: { $ne: 'cancelled' } } },
      { $unwind: '$products' },
      { $group: { _id: '$products.product', units: { $sum: '$products.quantity' }, revenue: { $sum: { $multiply: ['$products.quantity', '$products.priceAtSale'] } } } },
      { $sort: { revenue: -1 } },
      { $limit: 5 },
      { $lookup: { from: 'products', localField: '_id', foreignField: '_id', as: 'p' } },
    ]),
    Sale ? Sale.findOne({ tenantId: tid }).sort({ saleDate: -1 }).select('saleDate').lean() : null,
  ]);

  const sales = salesAgg[0] || { count: 0, revenue: 0, profit: 0 };
  const thisMonth = monthAgg.find((m) => m._id === 'this') || { revenue: 0, count: 0 };
  const lastMonth = monthAgg.find((m) => m._id === 'last') || { revenue: 0, count: 0 };
  const growthPct = lastMonth.revenue > 0
    ? Math.round(((thisMonth.revenue - lastMonth.revenue) / lastMonth.revenue) * 100)
    : (thisMonth.revenue > 0 ? 100 : 0);
  const stock = stockAgg[0] || { stockValue: 0, stockUnits: 0, outOfStock: 0, lowStock: 0 };
  const expenses = expenseAgg[0] || { total: 0, count: 0 };
  const outstanding = outstandingAgg[0] || { outstanding: 0, count: 0 };

  const statusBreakdown = Object.fromEntries(statusAgg.map((s) => [s._id || 'unknown', s.count]));

  // 6-month revenue trend (filled buckets, oldest → newest)
  const trendMap = Object.fromEntries(trendAgg.map((t) => [`${t._id.y}-${String(t._id.m).padStart(2, '0')}`, t.revenue]));
  const trend = [];
  for (let i = 5; i >= 0; i -= 1) {
    const d = new Date(now.getFullYear(), now.getMonth() - i, 1);
    const key = `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, '0')}`;
    trend.push({ month: key, revenue: Math.round(trendMap[key] || 0) });
  }

  const topProducts = topProductsAgg.map((t) => ({
    name: t.p?.[0]?.name || 'Produit supprimé',
    units: t.units || 0,
    revenue: Math.round(t.revenue || 0),
  }));

  res.json({
    tenant: { _id: tenant._id, name: tenant.name, code: tenant.code, plan: tenant.plan, status: tenant.status, createdAt: tenant.createdAt },
    counts: {
      products: productCount, clients: clientCount, employees: employeeCount,
      users: userCount, activeUsers,
    },
    sales: {
      total: sales.count,
      revenue: Math.round(sales.revenue || 0),
      profit: Math.round(sales.profit || 0),
      thisMonthRevenue: Math.round(thisMonth.revenue || 0),
      lastMonthRevenue: Math.round(lastMonth.revenue || 0),
      thisMonthCount: thisMonth.count,
      growthPct,
      statusBreakdown,
      lastSaleDate: lastSale?.saleDate || null,
      avgTicket: sales.count > 0 ? Math.round((sales.revenue || 0) / sales.count) : 0,
    },
    outstanding: { amount: Math.round(outstanding.outstanding || 0), count: outstanding.count },
    stock: {
      value: Math.round(stock.stockValue || 0),
      units: stock.stockUnits || 0,
      outOfStock: stock.outOfStock || 0,
      lowStock: stock.lowStock || 0,
    },
    expenses: { total: Math.round(expenses.total || 0), count: expenses.count },
    netResult: Math.round((sales.profit || 0) - (expenses.total || 0)),
    trend,
    topProducts,
    generatedAt: new Date().toISOString(),
  });
});

// ── Super-admin: read the editable plan catalog ──
// GET /api/tenants/plans
const getPlans = asyncHandler(async (req, res) => {
  const cfg = await PlatformConfig.getCatalog();
  // Return the *effective* feature list per plan (DB override, else code
  // default) so the editor reflects what shops actually get.
  const out = {};
  ['trial', 'basic', 'pro', 'enterprise'].forEach((key) => {
    const p = (cfg.plans && cfg.plans[key]) || {};
    out[key] = {
      label: p.label || '',
      price: p.price ?? 0,
      maxUsers: p.maxUsers ?? 1,
      maxProducts: p.maxProducts ?? 1,
      features: effectivePlanFeatures(key, Array.from(p.features || [])),
    };
  });
  res.json(out);
});

// ── Super-admin: update the plan catalog (prices + limits) ──
// PUT /api/tenants/plans
const updatePlans = asyncHandler(async (req, res) => {
  const cfg = await PlatformConfig.getCatalog();
  const incoming = req.body.plans || req.body;

  ['trial', 'basic', 'pro', 'enterprise'].forEach((key) => {
    const p = incoming[key];
    if (!p) return;
    if (p.label !== undefined)       cfg.plans[key].label = String(p.label);
    if (p.price !== undefined)       cfg.plans[key].price = Math.max(0, Number(p.price) || 0);
    if (p.maxUsers !== undefined)    cfg.plans[key].maxUsers = Math.max(1, Number(p.maxUsers) || 1);
    if (p.maxProducts !== undefined) cfg.plans[key].maxProducts = Math.max(1, Number(p.maxProducts) || 1);
    if (Array.isArray(p.features))   cfg.plans[key].features = p.features.map(String);
  });

  await cfg.save();
  invalidateFeatureCache();

  PlatformAudit.record({ req, action: 'plans.update', tenant: null, meta: {} });

  res.json(cfg.plans);
});

// ── Shop: list of available plans (labels, prices, limits) for the chooser ──
// GET /api/tenants/plan-catalog
const getPlanCatalog = asyncHandler(async (req, res) => {
  const keys = ['trial', 'basic', 'pro', 'enterprise'];
  const plans = {};
  for (const k of keys) {
    const p = await resolvePlan(k);
    plans[k] = { key: k, ...p, features: effectivePlanFeatures(k, Array.from(p.features || [])) };
  }
  res.json({ plans });
});

// ── Shop admin: request a plan change (sent to the super-admin) ──
// POST /api/tenants/plan-request   { requestedPlan, note }
const requestPlanChange = asyncHandler(async (req, res) => {
  if (!req.tenantId) { res.status(400); throw new Error('Aucune boutique active.'); }
  const { requestedPlan, note } = req.body;
  if (!['basic', 'pro', 'enterprise'].includes(requestedPlan)) {
    res.status(400); throw new Error('Plan demandé invalide.');
  }
  const tenant = await Tenant.findById(req.tenantId);
  if (!tenant) { res.status(404); throw new Error('Boutique introuvable.'); }

  tenant.planRequest = {
    requestedPlan,
    note: String(note || '').trim().slice(0, 400),
    status: 'pending',
    requestedAt: new Date(),
    requestedBy: req.user?._id || null,
  };
  await tenant.save();
  res.status(201).json({ success: true, planRequest: tenant.planRequest });
});

// ── Super-admin: approve / reject a tenant's plan-change request ──
// PUT /api/tenants/:id/plan-request   { action: 'approve' | 'reject' }
const resolvePlanRequest = asyncHandler(async (req, res) => {
  const { action } = req.body;
  const tenant = await Tenant.findById(req.params.id);
  if (!tenant) { res.status(404); throw new Error('Boutique introuvable.'); }
  if (!tenant.planRequest || tenant.planRequest.status !== 'pending') {
    res.status(400); throw new Error('Aucune demande de plan en attente.');
  }

  if (action === 'approve') {
    const target = tenant.planRequest.requestedPlan;
    const preset = await resolvePlan(target);
    tenant.plan = target;
    if (preset) {
      tenant.maxUsers = preset.maxUsers;
      tenant.maxProducts = preset.maxProducts;
      tenant.monthlyPrice = preset.price;
    }
    tenant.status = 'active';
    tenant.subscriptionEndsAt = new Date(Date.now() + 30 * 86400000);
    tenant.planRequest.status = 'approved';
  } else if (action === 'reject') {
    tenant.planRequest.status = 'rejected';
  } else {
    res.status(400); throw new Error('Action invalide.');
  }
  await tenant.save();
  res.json({ success: true, tenant });
});

module.exports = {
  registerTenant,
  createTenant,
  getTenants,
  getPlanCatalog,
  requestPlanChange,
  resolvePlanRequest,
  getTenantById,
  updateTenant,
  deleteTenant,
  getMyTenant,
  impersonateTenant,
  exportTenantsCsv,
  getOverviewStats,
  recordPayment,
  getAuditLog,
  getPlans,
  updatePlans,
  getTenantStats,
};
